config/routes.rb
Rails.application.routes.draw do
  resources :requests, only: [:destroy] do 
    patch 'create', to: 'requests#create', on: :member
    patch 'accept', on: :member
  end
  
  devise_for :users, :controllers => { :users => "users" }
  resources :users, only: [:show, :edit, :update]

  resources :teams do 
    patch 'kick', on: :member
  end


  root "teams#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :team

  def user_name
    "#{user.first_name}"
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :users
  has_many :requests, dependent: :destroy

  MAX_SIZE = 3 # team leader is included to make 4
 
  validates :name, presence: true

  def full?
    users.count == MAX_SIZE 
  end

  def user_in_team?(user)
    users.include?(user)
  end

  def leader
    User.find(lead.to_i)
  end

  def empty?
    !users.present?
  end

  def user_requested?(user)
    Request.pluck(:user_id).include?(user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :team, optional: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true 
  
  def is_team_lead?
    Team.pluck(:lead).map(&:to_i).include?(id)
  end

  def team_leading
    Team.find_by_lead(id.to_s)
  end

  def in_team?
    Team.joins(:users).pluck(:id).include?(id) or Team.pluck(:lead).map(&:to_i).include?(id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def team_request
    Request.find_by_user_id(id.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!


end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[ destroy accept ]

  def create
    if !current_user.first_name.present?
      redirect_to edit_user_url(current_user), notice: "Please update your account information first" and return
    end
    
    Request.new(team_id: params[:team].to_i, user_id: current_user.id).save
    redirect_to Team.find(params[:team].to_i), notice: "Request made" and return
  end

  def accept
    @request.team.users << @request.user
    @request.destroy
    redirect_to @request.team, notice: "User accepted"
  end

  def destroy
    @request.destroy
    redirect_to @request.team, notice: "User declined"
  end

  private
    def set_request
      @request = Request.find(params[:id])
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy kick ]

  def index
    @teams = Team.all
  end

  def show
    @users = @team.users
    @requests = @team.requests
  end

  def new
    if !current_user.first_name.present?
      redirect_to edit_user_url(current_user), notice: "Please update your account information first" and return
    end

    @team = Team.new
  end

  def edit
    if !@team.leader
      redirect_to @team
    end
  end

  def create
    @team = Team.new(team_params)
    @team.lead = current_user.id
    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def kick
    @team.users.delete(params[:user_id].to_i)
    redirect_to @team, notice: "User kicked"
  end

  private
    def set_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.require(:team).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if current_user.id != @user.id
      redirect_to root_path
    end
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :github, :facebook, :twitter, :about)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    date.strftime("%b %-d, %Y")
  end

  def blank_to_human(potential_blank)
    potential_blank.present? ? potential_blank : "nothing to show"
  end

  def toastr_flash
    flash.each_with_object([]) do |(type, message), flash_messages|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert'
      text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true })</script>"
      flash_messages << text.html_safe if message
    end.join("\n").html_safe
  end  

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def team_lead?(team)
    current_user == team.leader
  end

  def can_join_team?(team)
    !current_user.in_team? and !team.user_requested?(current_user)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Dory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if current_user %>
    <body>
      <%= toastr_flash %>
      <%= render 'shared/navtop' %>
      <main>
        <%= yield %>
      </main>
      <%= render 'shared/footer' %>
    </body>
  <% else %>
    <body class="text-center custom-body" data-new-gr-c-s-check-loaded="14.993.0" data-gr-ext-installed contenteditable="false">
      <main class="form-signin">
        <%= yield %>
      </main>
    </body>
  <% end %>
</html>

app/views/requests/_form.html.erb
<%= simple_form_for(@request) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :team %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.user_id %></td>
        <td><%= request.team_id %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @request.user_id %>
</p>

<p>
  <strong>Team:</strong>
  <%= @request.team_id %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row align-items-center no-gutters border-top py-2">
      <!-- Desc -->
      <div class="col-md-6 col-12">
        <span>Copyright © <%= DateTime.now.year %> Project Dory All rights reserved.</span>
        <a href="https://github.com/Smallz2/project-dory" target="_blank">Project Github</a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navtop.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-sm">
  <%= link_to "Project Dory", root_path, class: "h5 my-0 me-md-auto fw-normal navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse me-md-auto" id="navbar-list-4">
    <ul class="navbar-nav">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg" width="40" height="40" class="rounded-circle">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>   
    </ul>
  </div>
</nav>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :github %>
    <%= f.input :facebook %>
    <%= f.input :twitter %>
    <%= f.input :about, 
                :input_html => { placeholder: "Tell us about yourself" } %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary mb-4" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="bg-primary">
  <div class="container py-5">
    <!-- Hero Section -->
    <div class="row align-items-center no-gutters">
      <div class="col-xl-5 col-lg-6 col-md-12">
        <div class="py-5 py-lg-0">
          <h1 class="text-white display-4 font-weight-bold">Editing User
          </h1>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="py-5 container">
  <%= render 'form', user: @user %>

  <%= link_to 'Back', @user %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="bg-primary">
  <div class="container py-5">
    <!-- Hero Section -->
    <div class="row align-items-center no-gutters">
      <div class="col-xl-5 col-lg-6 col-md-12">
        <div class="py-5 py-lg-0">
          <h1 class="text-white display-4 font-weight-bold"><%= blank_to_human(@user.full_name) %>
          </h1>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container py-5">
  <div class="col-lg-12 p-0">
    <div class="card border-0 mb-4">
      <!-- Card body -->
      <div class="card-body">
        <h4>About me</h4>
        <p>
          <%= blank_to_human(@user.about) %>
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4 col-md-4 col-12">
      <!-- Card -->
      <div class="card border-0 mb-4 mb-lg-0">
        <!-- Card body -->
        <div class="card-body">
          <div class="d-flex align-items-center justify-content-between border-bottom pb-3 mb-3">
            <div>
              <h4 class="mb-0 font-weight-bold">Github</h4>
              <% if @user.github.present? %>
                <a href="<%= @user.github %>" target="_blank">link</a>
              <% end %>
            </div>
            <div>
              <span><i class="fe fe-file-text font-size-lg"></i></span>
            </div>
          </div>
          <div class="d-flex align-items-center justify-content-between border-bottom pb-3 mb-3">
            <div>
              <h4 class="mb-0 font-weight-bold">Facebook</h4>
              <% if @user.facebook.present? %>
                <a href="<%= @user.facebook %>" target="_blank">link</a>
              <% end %>
            </div>
            <div>
              <span><i class="fe fe-users font-size-lg"></i></span>
            </div>
          </div>
          <div class="d-flex align-items-center justify-content-between">
            <div>
              <h4 class="mb-0 font-weight-bold">Twitter</h4>
              <% if @user.twitter.present? %>
                <a href="<%= @user.twitter %>" target="_blank">link</a>
              <% end %>
            </div>
            <div>
              <span><i class="fe fe-star font-size-lg"></i></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>